### PR TITLE
feat: add directus îles example (https://iles.pages.dev)

### LINKED ISSUE #88: Add Iles example
Please add iles example. https://iles.pages.dev/ 

iles is different enough from the Vue and Nuxt setups that it deserves its own example.

### PR DESCRIPTION
**Pull request by ElMassimo**
Closes #88

This pull request adds an example of how to integrate Directus in an [îles](https://iles.pages.dev/) project.

iles

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Thanks @ElMassimo!

**Review by azrikahar — APPROVED** [review]
LGTM! Tested locally and works great. Perhaps we can coordinate to get a guide for this example added to https://github.com/directus/guides 👍

**Comment by erondpowell** [comment]
> LGTM! Tested locally and works great. Perhaps we can coordinate to get a guide for this example added to https://github.com/directus/guides 👍

@rijkvanzanten You want me to do that? I'm ready for it 🤠

**Comment by rijkvanzanten** [comment]
Sure thing! Lets do it 🙂 

@ElMassimo As lead maintainer of Îles, mind factchecking what we come up with?

**Comment by ElMassimo** [comment]
Sounds good, ping me and I'll take a look 😃

**Comment by erondpowell** [comment]
> Sure thing! Lets do it 🙂

Sweet. I have a few things on the agenda this week, plan to have it done by Monday.

**Comment by erondpowell** [comment]
@ElMassimo We are going to make a photo like this for iles:

Screen Shot 2022-04-12 at 8 54 28 AM
 
Can you send an "Iles" logo over as a PNG? How about an image? (I can get an image of some totally sweet island if you don't have a specific island in mind.)


You can send it in this thread or email me at eron@directus.io

**Comment by rijkvanzanten** [comment]
(regarding the image, lets make sure it's licensed in a way that allows this sort of usage. Finding something on unsplash.com is a great way to ensure that)

**Comment by ElMassimo** [comment]
Great! Feel free to use any background image 😃 🌴 

- [SVG of the logo](https://github.com/ElMassimo/iles/blob/main/docs/icons/text.svg?short_path=75ee2c3).
- [PNG of the logo](https://github.com/ElMassimo/iles/blob/main/docs/images/banner.png), for reference

**Pull request merged**
