### PR TITLE
Example with Quasar Framework

### PR DESCRIPTION
**Pull request by rashidpathiyil**
Example with Quasar Framework
 

- [x] Setup Directus SDK
- [x] Add basic authentication with Directus SDK

Ref #133 

https://user-images.githubusercontent.com/15140041/181167653-27bd3f9a-9a8b-45b5-a212-91e8c34652b1.mp4

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Would it be possible to use the same design / structure as every other example? Right now, there's a nice consistency going on between the frameworks, where they all generate the same basic blog example 🤔  That makes it way easier to compare the different implementations and see how the SDK is used in the various contexts

**Comment by azrikahar** [comment]
I do share the same sentiment as @rijkvanzanten here, and making it easier to compare was also one of the main goal from the start. With that said, I can also understand that an argument can be made whether the blog example fits the nature of Quasar in the sense of an app perspective.

In regards to UnoCSS, I do agree that it technically provides finer grained control similar to Tailwind CSS, compared to more opinionated UI libraries, so it's not as "heavy". However it does feel a tad opinionated in the sense that this now feels more like a template starter vs making it easier for new devs to digest since it's still 1 more moving parts into the mix here.

**Comment by rijkvanzanten** [comment]
> like a template starter vs making it easier for new devs to digest since it's still 1 more moving parts into the mix here.

I think that's my main "issue" here! Well put. The current _examples_ repo is showing _examples_ of how to use Directus in a minimal frame of your favorite framework. It's not full starter projects that include full styling frameworks etc. Keeping it simple allows us to highlight how to inject Directus, rather than confuse things with unrelated opinionated parts 🙂

**Comment by azrikahar** [comment]
Hi @rashidpathiyil, just wondering did you have a chance to look at the comments above? Would love to get to know your perspective on them. 👍

**Comment by rashidpathiyil** [comment]
Yea, I agree with you statement 👍. I will look in to it later.

**Pull request closed without merging**
